version: '3.2'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "22181:2181"
    env_file:
      - config/zookeeper.env

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    env_file:
      - config/kafka.env

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - config/database.env
    volumes:
      - ~/docker/volumes/postgres:/var/lib/postgresql/data
